uint64 timestamp	# time since system start (microseconds)

float32 true_gyro0
float32 true_gyro1
float32 true_gyro2
float32 cmd_gyro0
float32 cmd_gyro1
float32 cmd_gyro2

float32 true_accel0
float32 true_accel1
float32 true_accel2
float32 cmd_accel0
float32 cmd_accel1
float32 cmd_accel2


float32 true_q0
float32 true_q1
float32 true_q2
float32 true_q3
float32 cmd_q0
float32 cmd_q1
float32 cmd_q2
float32 cmd_q3
